### ISSUE TITLE
UTC time stamp confusion

### ISSUE THREAD

**Issue by stefferber** [EnergyID/smappy#11]
I do not understand the difference in results for two similar queries. Do I use the python time wrong?

``` python
>>> end_time = datetime.utcnow()
>>> start_time = end_time - timedelta(weeks=0, days=0, hours=1, minutes=0, seconds=00)
>>> start = 1000 * timegm(start_time.utctimetuple())
>>> end   = 1000 * timegm(end_time.utctimetuple())
>>> print(s.get_consumption(service_location_id, start_time, end_time, 1))
{'consumptions': [{'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 21.4, 'timestamp': 1477239000000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 23.9, 'timestamp': 1477239300000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 29.2, 'timestamp': 1477239600000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 36.1, 'timestamp': 1477239900000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 40.7, 'timestamp': 1477240200000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 41.2, 'timestamp': 1477240800000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 47.6, 'timestamp': 1477241100000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 47.4, 'timestamp': 1477241400000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 50.8, 'timestamp': 1477241700000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 55.9, 'timestamp': 1477242000000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 55.2, 'timestamp': 1477242300000}], 'serviceLocationId': 13463}
>>> print(s.get_consumption(service_location_id, start, end, 1))
{'consumptions': [{'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 56.1, 'timestamp': 1477246200000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 47.4, 'timestamp': 1477246500000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 46.9, 'timestamp': 1477246800000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 46.8, 'timestamp': 1477247100000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 47.2, 'timestamp': 1477247400000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 47.2, 'timestamp': 1477247700000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 45.8, 'timestamp': 1477248000000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 45.1, 'timestamp': 1477248300000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 47.4, 'timestamp': 1477248600000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 46.9, 'timestamp': 1477248900000}, {'alwaysOn': 66.0, 'solar': 0.0, 'consumption': 46.8, 'timestamp': 1477249200000}], 'serviceLocationId': 13463}
>>> 

```

the first time stamp is 2h too early
`1477239000000 => GMT: Sun, 23 Oct 2016 16:10:00 GMT Your time zone: 23.10.2016, 18:10:00 GMT+2:00 DST`
and the second time stamp is correct
`1477246200000 => GMT: Sun, 23 Oct 2016 18:10:00 GMT Your time zone: 23.10.2016, 20:10:00 GMT+2:00 DST`

The [official API is asking for UTC](https://smappee.atlassian.net/wiki/display/DEVAPI/Get+Consumption) time though.

**Comment by JrtPec** [comment]
It took me a while to figure this one out, but here it goes:

If you pass a datetime object, the `timestamp()` method will be used to convert to milliseconds sinds epoch. [From the docs](https://docs.python.org/3.5/library/datetime.html#datetime.datetime.timestamp): 

> Naive datetime instances are assumed to represent local time

The problem is that `datetime.utcnow()` does not return a timezone-aware object (I think it should). It returns a timezone-naive object, which is not local, and `timestamp()` will be wrong.

So, right now, you have three options to get the correct data:

1. Supply a timezone-naive and local datetime object: `datetime.now()`
2. Supply a timezone-aware object: `import pytz; datetime.now(tz=pytz.utc)` or use a time library which does return a tz-aware object out of the box: `import pandas as pd; pd.Timestamp.utcnow()`
3. Supply the timestamp yourself.

I must admit this is very confusing. Basically it comes down to this question:
If a user supplies a timezone-naive datetime object, do we assume it is UTC or Local?

If local, nothing changes, but you'll just have to use `datetime.now()` instead of `datetime.utcnow()`. Otherwise I propose to treat all naive times as UTC, like this:
```python
if isinstance(time, dt.datetime) and time.tzinfo is None:
    time = time.replace(tzinfo=pytz.utc)
```
I would then make it very clear that times should either be timezone-aware OR in UTC.

What do you think?

**Comment by stefferber** [comment]
I don't know a straight answer but I think the following criteria might be helpful:

1. consistency: the official API specifies UTC
2. Model-View-Control pattern: Only "View" should use the local time and all the problems with summer/winter time. This API is more on the model side. 

As I do not know how this is tackled in python in other cases...

**Comment by JrtPec** [comment]
I agree. Basically what we're saying is this:

If a timezone-naive datetime is passed, we will assume that it is in UTC.

I will prepare a fix.

**Comment by JrtPec** [comment]
staged for next release

**Comment by stefferber** [comment]
@JrtPec Great! and Thx ;-)
