### ISSUE TITLE
Datetime workaround for python 2.7

### ISSUE THREAD

**Issue by serge-b** [EnergyID/smappy#4]
Hi there,
datetime doesn't have a timestamp() method in python 2.7
to make it fully compatible, I used a function timestamp to wrap around utcnow() :
```
def timestamp_milli(t):
    return int((t - dt.datetime(1970, 1, 1)).total_seconds())*1000

```
This way, you send an int to the Smappee object get_consumption_xxx methods.
Hope this helps...
Serge

**Comment by JrtPec** [comment]
Hey Serge,

I'm a little bit torn, because I never intended to make this module compatible with python2... (more testing and complexity + I think people should move to PY3 already). But if you really need it to be compatible I guess I could do an effort.

Is it only the datetime.timestamp part that gives you issues?

**Comment by JrtPec** [comment]
Hi @serge-b, I'm marking this as a wontfix because I don't want to maintain workarounds for legacy Python versions, sorry.

However, you might already have noticed that the `get_consumption` methods accept multiple datetime formats, including int (as milliseconds sinds epoch). So I believe that as long as you pass an int to those methods, the code should work just fine in python 2.7
